// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_reputation.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getAttachmentReputation = `-- name: GetAttachmentReputation :one
SELECT sha256, provider, state, detected, total, threat_name, analysed_at, fetched_at FROM attachment_reputation
WHERE sha256 = $1 AND provider = $2
`

type GetAttachmentReputationParams struct {
	Sha256   string `json:"sha256"`
	Provider string `json:"provider"`
}

// The cached verdict for one hash from one provider.
//
// Both halves of the key are required. Reading by hash alone would return
// whichever provider happened to answer first and attribute it to the one the
// operator has configured.
func (q *Queries) GetAttachmentReputation(ctx context.Context, arg GetAttachmentReputationParams) (AttachmentReputation, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentReputation, arg.Sha256, arg.Provider)
	var i AttachmentReputation
	err := row.Scan(
		&i.Sha256,
		&i.Provider,
		&i.State,
		&i.Detected,
		&i.Total,
		&i.ThreatName,
		&i.AnalysedAt,
		&i.FetchedAt,
	)
	return i, err
}

const upsertAttachmentReputation = `-- name: UpsertAttachmentReputation :one
INSERT INTO attachment_reputation (
    sha256, provider, state, detected, total, threat_name, analysed_at, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (sha256, provider) DO UPDATE
SET state       = EXCLUDED.state,
    detected    = EXCLUDED.detected,
    total       = EXCLUDED.total,
    threat_name = EXCLUDED.threat_name,
    analysed_at = EXCLUDED.analysed_at,
    fetched_at  = EXCLUDED.fetched_at
RETURNING sha256, provider, state, detected, total, threat_name, analysed_at, fetched_at
`

type UpsertAttachmentReputationParams struct {
	Sha256     string         `json:"sha256"`
	Provider   string         `json:"provider"`
	State      string         `json:"state"`
	Detected   sql.NullInt32  `json:"detected"`
	Total      sql.NullInt32  `json:"total"`
	ThreatName sql.NullString `json:"threat_name"`
	AnalysedAt sql.NullTime   `json:"analysed_at"`
}

// Records a completed lookup.
//
// An upsert rather than an insert because two staff members can open the same
// ticket at once: without ON CONFLICT the second lookup fails on the primary
// key and an ordinary page render errors.
//
// fetched_at is the database's clock, not Go's, for the same reason sessions
// stopped passing a timestamp in: one clock decides one timeline. now() rather
// than clock_timestamp() is fine here — nothing compares this value against an
// expiry, it is only shown to a person.
func (q *Queries) UpsertAttachmentReputation(ctx context.Context, arg UpsertAttachmentReputationParams) (AttachmentReputation, error) {
	row := q.db.QueryRowContext(ctx, upsertAttachmentReputation,
		arg.Sha256,
		arg.Provider,
		arg.State,
		arg.Detected,
		arg.Total,
		arg.ThreatName,
		arg.AnalysedAt,
	)
	var i AttachmentReputation
	err := row.Scan(
		&i.Sha256,
		&i.Provider,
		&i.State,
		&i.Detected,
		&i.Total,
		&i.ThreatName,
		&i.AnalysedAt,
		&i.FetchedAt,
	)
	return i, err
}
