// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_reputation.sql

package dbgen

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getAttachmentReputation = `-- name: GetAttachmentReputation :one
SELECT sha256, provider, state, detected, total, known_feeds, threat_name, analysed_at, fetched_at FROM attachment_reputation
WHERE sha256 = $1 AND provider = $2
`

type GetAttachmentReputationParams struct {
	Sha256   string `json:"sha256"`
	Provider string `json:"provider"`
}

// The cached verdict for one hash from one provider.
//
// Both halves of the key are required. Reading by hash alone would return
// whichever provider happened to answer first and attribute it to the one the
// operator has configured.
func (q *Queries) GetAttachmentReputation(ctx context.Context, arg GetAttachmentReputationParams) (AttachmentReputation, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentReputation, arg.Sha256, arg.Provider)
	var i AttachmentReputation
	err := row.Scan(
		&i.Sha256,
		&i.Provider,
		&i.State,
		&i.Detected,
		&i.Total,
		pq.Array(&i.KnownFeeds),
		&i.ThreatName,
		&i.AnalysedAt,
		&i.FetchedAt,
	)
	return i, err
}

const upsertAttachmentReputation = `-- name: UpsertAttachmentReputation :one
INSERT INTO attachment_reputation (
    sha256, provider, state, detected, total, threat_name, analysed_at,
    known_feeds, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($8::text[], '{}'), clock_timestamp())
ON CONFLICT (sha256, provider) DO UPDATE
SET state            = EXCLUDED.state,
    detected         = EXCLUDED.detected,
    total            = EXCLUDED.total,
    threat_name      = EXCLUDED.threat_name,
    analysed_at      = EXCLUDED.analysed_at,
    known_feeds = EXCLUDED.known_feeds,
    fetched_at       = EXCLUDED.fetched_at
RETURNING sha256, provider, state, detected, total, known_feeds, threat_name, analysed_at, fetched_at
`

type UpsertAttachmentReputationParams struct {
	Sha256     string         `json:"sha256"`
	Provider   string         `json:"provider"`
	State      string         `json:"state"`
	Detected   sql.NullInt32  `json:"detected"`
	Total      sql.NullInt32  `json:"total"`
	ThreatName sql.NullString `json:"threat_name"`
	AnalysedAt sql.NullTime   `json:"analysed_at"`
	KnownFeeds []string       `json:"known_feeds"`
}

// Records a completed lookup.
//
// An upsert rather than an insert because two staff members can open the same
// ticket at once: without ON CONFLICT the second lookup fails on the primary
// key and an ordinary page render errors.
//
// fetched_at is the database's clock, not Go's, for the same reason sessions
// stopped passing a timestamp in: one clock decides one timeline.
//
// clock_timestamp() rather than now(): #168 made this value the one two
// refresh rules are decided on, and now() is the transaction's start time, not
// the statement's. Two writes inside one transaction get the same stamp, and a
// verdict written late in a long transaction is backdated to whenever that
// transaction opened. Both errors point the same way — a row that looks older
// than it is, re-checked sooner than it should be, out of an allowance that is
// not ours.
//
// Every write re-stamps it, including one that changes nothing, which is what
// makes a re-check that comes back with the same answer still count as a
// re-check.
//
// known_feeds is COALESCEd because the column is NOT NULL while the parameter
// is optional: only a "known" verdict has feeds, and every other caller passes
// nothing. A nil parameter therefore has to mean "no feeds"
// rather than violating the constraint — the column's DEFAULT does not apply
// when a value is given explicitly, even a null one.
func (q *Queries) UpsertAttachmentReputation(ctx context.Context, arg UpsertAttachmentReputationParams) (AttachmentReputation, error) {
	row := q.db.QueryRowContext(ctx, upsertAttachmentReputation,
		arg.Sha256,
		arg.Provider,
		arg.State,
		arg.Detected,
		arg.Total,
		arg.ThreatName,
		arg.AnalysedAt,
		pq.Array(arg.KnownFeeds),
	)
	var i AttachmentReputation
	err := row.Scan(
		&i.Sha256,
		&i.Provider,
		&i.State,
		&i.Detected,
		&i.Total,
		pq.Array(&i.KnownFeeds),
		&i.ThreatName,
		&i.AnalysedAt,
		&i.FetchedAt,
	)
	return i, err
}
