// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countAuditLog = `-- name: CountAuditLog :one
WITH visible AS MATERIALIZED (
  SELECT t.id FROM tickets t
  WHERE $7::uuid IS NOT NULL
    AND (
      t.reporter_user_id = $7::uuid
      OR t.assignee_user_id = $7::uuid
      OR t.assignee_group_id IN (SELECT gm.group_id FROM group_members gm WHERE gm.user_id = $7::uuid)
      OR t.category_id IN (
        SELECT gs.category_id FROM group_scopes gs
        JOIN group_members gm ON gm.group_id = gs.group_id
        WHERE gm.user_id = $7::uuid AND gs.type_id IS NULL
      )
      OR (t.category_id, t.type_id) IN (
        SELECT gs.category_id, gs.type_id FROM group_scopes gs
        JOIN group_members gm ON gm.group_id = gs.group_id
        WHERE gm.user_id = $7::uuid AND gs.type_id IS NOT NULL
      )
    )
)
SELECT COUNT(*) FROM (
  SELECT 1 FROM audit_log
  WHERE ($1::text IS NULL OR entity_type = $1::text)
    AND ($2::text IS NULL OR action = $2::text)
    AND ($3::uuid IS NULL OR actor_id = $3::uuid)
    AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
    AND (
      $6::text IS NULL
      OR entity_type ILIKE '%' || $6::text || '%'
      OR action ILIKE '%' || $6::text || '%'
    )
    -- Staff scope (#330): NULL means no restriction; otherwise ticket entries
    -- on a visible ticket only. An entry whose ticket is gone matches nothing,
    -- which is what "not yours" looks like too.
    AND (
      $7::uuid IS NULL
      OR (entity_type = 'ticket' AND entity_id IN (SELECT id FROM visible))
    )
  LIMIT $8
) AS matched
`

type CountAuditLogParams struct {
	EntityType sql.NullString `json:"entity_type"`
	Action     sql.NullString `json:"action"`
	ActorID    uuid.NullUUID  `json:"actor_id"`
	FromTs     sql.NullTime   `json:"from_ts"`
	ToTs       sql.NullTime   `json:"to_ts"`
	Q          sql.NullString `json:"q"`
	ScopedTo   uuid.NullUUID  `json:"scoped_to"`
	CountCap   int32          `json:"count_cap"`
}

// Same filters as SearchAuditLog, scope included, but BOUNDED: it counts at most
// count_cap matches and stops, so the cost is that of finding count_cap rows,
// not of scanning a table nobody prunes (#331). The caller asks for the cap
// plus one and reads "more than the cap" off the result; an answer at or under
// the cap is exact. Scope applies here too, so a staff member is counted only
// what they can see.
//
// The staff scope is the same predicate as SearchAuditLog's, over the same
// tickets columns, but arranged the other way round: the visible tickets are
// found first, then the audit rows on them. As SearchAuditLog's per-row EXISTS
// inside a LIMIT the planner assumes matches are plentiful and walks the whole
// entity index looking for them; for a staff member who sees few tickets that
// was measured at 3x slower than the unbounded count (411 ms against 143 ms at
// 524k audit rows / 30k tickets), which is the opposite of a bound. The
// MATERIALIZED set is empty, and never read, when scoped_to is NULL.
//
// The Category/Type rule is written as two IN lists, not as the per-ticket
// EXISTS the page query uses, so each list is built once and the set costs one
// pass over tickets rather than one subplan run per ticket (measured: a staff
// count with a narrow filter fell from ~125-165 ms to ~5-40 ms). The meaning is
// the same: a rule without a type covers its whole category, tickets without a
// type included; a rule with a type covers that type only, and the row
// comparison is not true for a ticket whose type is NULL, which stays hidden.
// IN does not repeat a ticket reached by several groups. The tests in
// auditstore_scope_rules_test.go state this in Go and hold both queries to it.
func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLog,
		arg.EntityType,
		arg.Action,
		arg.ActorID,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
		arg.ScopedTo,
		arg.CountCap,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_log (id, actor_id, entity_type, entity_id, action, before, after, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditEntryParams struct {
	ID         uuid.UUID             `json:"id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.UUID             `json:"entity_id"`
	Action     string                `json:"action"`
	Before     pqtype.NullRawMessage `json:"before"`
	After      pqtype.NullRawMessage `json:"after"`
	CreatedAt  time.Time             `json:"created_at"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEntry,
		arg.ID,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.CreatedAt,
	)
	return err
}

const deleteAuditLogBefore = `-- name: DeleteAuditLogBefore :execrows
DELETE FROM audit_log WHERE created_at < $1
`

// The retention sweep's hard delete. No archive table — see audit.Store's
// own comment on DeleteOlderThan for why.
func (q *Queries) DeleteAuditLogBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditLogBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAuditByEntity = `-- name: ListAuditByEntity :many
SELECT id, actor_id, entity_type, entity_id, action, before, after, created_at FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListAuditByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListAuditByEntity(ctx context.Context, arg ListAuditByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAuditLog = `-- name: SearchAuditLog :many
SELECT id, actor_id, entity_type, entity_id, action, before, after, created_at FROM audit_log
WHERE ($1::text IS NULL OR entity_type = $1::text)
  AND ($2::text IS NULL OR action = $2::text)
  AND ($3::uuid IS NULL OR actor_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
  AND (
    $6::text IS NULL
    OR entity_type ILIKE '%' || $6::text || '%'
    OR action ILIKE '%' || $6::text || '%'
  )
  -- Staff scope (#330). NULL means no restriction. Otherwise only ticket
  -- entries on a ticket the staff member with this id may see: the same four
  -- ways in as ListTicketsFiltered and ticket.CanView — reported by them,
  -- assigned to them, assigned to a group of theirs, or inside a Category/Type
  -- a group of theirs covers. An entry whose ticket is gone matches nothing
  -- here, which is what "not yours" looks like too.
  AND (
    $7::uuid IS NULL
    OR (
      entity_type = 'ticket'
      AND EXISTS (
        SELECT 1 FROM tickets t
        WHERE t.id = audit_log.entity_id
          AND (
            t.reporter_user_id = $7::uuid
            OR t.assignee_user_id = $7::uuid
            OR t.assignee_group_id IN (SELECT gm.group_id FROM group_members gm WHERE gm.user_id = $7::uuid)
            OR EXISTS (
              SELECT 1 FROM group_scopes gs
              JOIN group_members gm ON gm.group_id = gs.group_id
              WHERE gm.user_id = $7::uuid
                AND gs.category_id = t.category_id
                AND (gs.type_id IS NULL OR gs.type_id = t.type_id)
            )
          )
      )
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $9 OFFSET $8
`

type SearchAuditLogParams struct {
	EntityType sql.NullString `json:"entity_type"`
	Action     sql.NullString `json:"action"`
	ActorID    uuid.NullUUID  `json:"actor_id"`
	FromTs     sql.NullTime   `json:"from_ts"`
	ToTs       sql.NullTime   `json:"to_ts"`
	Q          sql.NullString `json:"q"`
	ScopedTo   uuid.NullUUID  `json:"scoped_to"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

// The admin-wide audit view (#129). Every filter is optional, and scoped_to
// narrows to the tickets one staff member may see; see audit.Filter.
// id breaks the tie, because created_at alone does not order entries written
// in the same microsecond — which happens inside a single request. Without a
// total order, two pages of one listing can disagree about which tied row
// comes first and the same entry appears twice, or not at all.
func (q *Queries) SearchAuditLog(ctx context.Context, arg SearchAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, searchAuditLog,
		arg.EntityType,
		arg.Action,
		arg.ActorID,
		arg.FromTs,
		arg.ToTs,
		arg.Q,
		arg.ScopedTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
