// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_log (id, actor_id, entity_type, entity_id, action, before, after, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditEntryParams struct {
	ID         uuid.UUID             `json:"id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.UUID             `json:"entity_id"`
	Action     string                `json:"action"`
	Before     pqtype.NullRawMessage `json:"before"`
	After      pqtype.NullRawMessage `json:"after"`
	CreatedAt  time.Time             `json:"created_at"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEntry,
		arg.ID,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.CreatedAt,
	)
	return err
}

const listAuditByEntity = `-- name: ListAuditByEntity :many
SELECT id, actor_id, entity_type, entity_id, action, before, after, created_at FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListAuditByEntity(ctx context.Context, arg ListAuditByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditByEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
