// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
	"github.com/lib/pq"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, name, hashed_token, user_id, scopes, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAPIKeyParams struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	HashedToken string       `json:"hashed_token"`
	UserID      uuid.UUID    `json:"user_id"`
	Scopes      []string     `json:"scopes"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.HashedToken,
		arg.UserID,
		pq.Array(arg.Scopes),
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :exec
INSERT INTO oauth_clients (id, client_id, hashed_secret, name, scopes, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOAuthClientParams struct {
	ID           uuid.UUID `json:"id"`
	ClientID     string    `json:"client_id"`
	HashedSecret string    `json:"hashed_secret"`
	Name         string    `json:"name"`
	Scopes       []string  `json:"scopes"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthClient,
		arg.ID,
		arg.ClientID,
		arg.HashedSecret,
		arg.Name,
		pq.Array(arg.Scopes),
		arg.CreatedAt,
	)
	return err
}

const createWebhookConfig = `-- name: CreateWebhookConfig :exec
INSERT INTO webhook_configs (id, url, events, secret, enabled, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookConfigParams struct {
	ID        uuid.UUID `json:"id"`
	Url       string    `json:"url"`
	Events    []string  `json:"events"`
	Secret    string    `json:"secret"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateWebhookConfig(ctx context.Context, arg CreateWebhookConfigParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookConfig,
		arg.ID,
		arg.Url,
		pq.Array(arg.Events),
		arg.Secret,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const deleteOAuthClient = `-- name: DeleteOAuthClient :exec
DELETE FROM oauth_clients WHERE id = $1
`

func (q *Queries) DeleteOAuthClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthClient, id)
	return err
}

const deleteWebhookConfig = `-- name: DeleteWebhookConfig :exec
DELETE FROM webhook_configs WHERE id = $1
`

func (q *Queries) DeleteWebhookConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookConfig, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, hashed_token, user_id, scopes, last_used_at, expires_at, created_at FROM api_keys WHERE hashed_token = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, hashedToken string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, hashedToken)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedToken,
		&i.UserID,
		pq.Array(&i.Scopes),
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, client_id, hashed_secret, name, scopes, created_at FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRowContext(ctx, getOAuthClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.HashedSecret,
		&i.Name,
		pq.Array(&i.Scopes),
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookConfig = `-- name: GetWebhookConfig :one
SELECT id, url, events, secret, enabled, created_at FROM webhook_configs WHERE id = $1
`

func (q *Queries) GetWebhookConfig(ctx context.Context, id uuid.UUID) (WebhookConfig, error) {
	row := q.db.QueryRowContext(ctx, getWebhookConfig, id)
	var i WebhookConfig
	err := row.Scan(
		&i.ID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, name, hashed_token, user_id, scopes, last_used_at, expires_at, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashedToken,
			&i.UserID,
			pq.Array(&i.Scopes),
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledWebhookConfigs = `-- name: ListEnabledWebhookConfigs :many
SELECT id, url, events, secret, enabled, created_at FROM webhook_configs WHERE enabled = TRUE ORDER BY created_at
`

func (q *Queries) ListEnabledWebhookConfigs(ctx context.Context) ([]WebhookConfig, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledWebhookConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookConfig
	for rows.Next() {
		var i WebhookConfig
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			pq.Array(&i.Events),
			&i.Secret,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, client_id, hashed_secret, name, scopes, created_at FROM oauth_clients ORDER BY name
`

func (q *Queries) ListOAuthClients(ctx context.Context) ([]OauthClient, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClient
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.HashedSecret,
			&i.Name,
			pq.Array(&i.Scopes),
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = $2 WHERE id = $1
`

type UpdateAPIKeyLastUsedParams struct {
	ID         uuid.UUID    `json:"id"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateWebhookConfig = `-- name: UpdateWebhookConfig :exec
UPDATE webhook_configs SET url = $2, events = $3, secret = $4, enabled = $5 WHERE id = $1
`

type UpdateWebhookConfigParams struct {
	ID      uuid.UUID `json:"id"`
	Url     string    `json:"url"`
	Events  []string  `json:"events"`
	Secret  string    `json:"secret"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) UpdateWebhookConfig(ctx context.Context, arg UpdateWebhookConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookConfig,
		arg.ID,
		arg.Url,
		pq.Array(arg.Events),
		arg.Secret,
		arg.Enabled,
	)
	return err
}
