// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canned_responses.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCannedResponse = `-- name: CreateCannedResponse :one
INSERT INTO canned_responses (id, name, body, category_id, type_id, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, body, category_id, type_id, sort_order, created_at
`

type CreateCannedResponseParams struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	Body       string        `json:"body"`
	CategoryID uuid.NullUUID `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
	SortOrder  int32         `json:"sort_order"`
}

func (q *Queries) CreateCannedResponse(ctx context.Context, arg CreateCannedResponseParams) (CannedResponse, error) {
	row := q.db.QueryRowContext(ctx, createCannedResponse,
		arg.ID,
		arg.Name,
		arg.Body,
		arg.CategoryID,
		arg.TypeID,
		arg.SortOrder,
	)
	var i CannedResponse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Body,
		&i.CategoryID,
		&i.TypeID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCannedResponse = `-- name: DeleteCannedResponse :exec
DELETE FROM canned_responses WHERE id = $1
`

func (q *Queries) DeleteCannedResponse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCannedResponse, id)
	return err
}

const getCannedResponse = `-- name: GetCannedResponse :one
SELECT id, name, body, category_id, type_id, sort_order, created_at FROM canned_responses WHERE id = $1
`

func (q *Queries) GetCannedResponse(ctx context.Context, id uuid.UUID) (CannedResponse, error) {
	row := q.db.QueryRowContext(ctx, getCannedResponse, id)
	var i CannedResponse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Body,
		&i.CategoryID,
		&i.TypeID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listCannedResponses = `-- name: ListCannedResponses :many
SELECT id, name, body, category_id, type_id, sort_order, created_at FROM canned_responses ORDER BY sort_order, name
`

func (q *Queries) ListCannedResponses(ctx context.Context) ([]CannedResponse, error) {
	rows, err := q.db.QueryContext(ctx, listCannedResponses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CannedResponse
	for rows.Next() {
		var i CannedResponse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Body,
			&i.CategoryID,
			&i.TypeID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCannedResponse = `-- name: UpdateCannedResponse :exec
UPDATE canned_responses
SET name = $2, body = $3, category_id = $4, type_id = $5, sort_order = $6
WHERE id = $1
`

type UpdateCannedResponseParams struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	Body       string        `json:"body"`
	CategoryID uuid.NullUUID `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
	SortOrder  int32         `json:"sort_order"`
}

func (q *Queries) UpdateCannedResponse(ctx context.Context, arg UpdateCannedResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateCannedResponse,
		arg.ID,
		arg.Name,
		arg.Body,
		arg.CategoryID,
		arg.TypeID,
		arg.SortOrder,
	)
	return err
}
