// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, name, sort_order, active) VALUES ($1, $2, $3, $4)
`

type CreateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Active    bool      `json:"active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	return err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO items (id, type_id, name, sort_order, active) VALUES ($1, $2, $3, $4, $5)
`

type CreateItemParams struct {
	ID        uuid.UUID `json:"id"`
	TypeID    uuid.UUID `json:"type_id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Active    bool      `json:"active"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.TypeID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	return err
}

const createType = `-- name: CreateType :exec
INSERT INTO types (id, category_id, name, sort_order, active) VALUES ($1, $2, $3, $4, $5)
`

type CreateTypeParams struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Name       string    `json:"name"`
	SortOrder  int32     `json:"sort_order"`
	Active     bool      `json:"active"`
}

func (q *Queries) CreateType(ctx context.Context, arg CreateTypeParams) error {
	_, err := q.db.ExecContext(ctx, createType,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const deleteType = `-- name: DeleteType :exec
DELETE FROM types WHERE id = $1
`

func (q *Queries) DeleteType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteType, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, sort_order, active FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, type_id, name, sort_order, active FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const getType = `-- name: GetType :one
SELECT id, category_id, name, sort_order, active FROM types WHERE id = $1
`

func (q *Queries) GetType(ctx context.Context, id uuid.UUID) (Type, error) {
	row := q.db.QueryRowContext(ctx, getType, id)
	var i Type
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.SortOrder,
		&i.Active,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, sort_order, active FROM categories
WHERE ($1::boolean = FALSE OR active = TRUE)
ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context, dollar_1 bool) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, type_id, name, sort_order, active FROM items
WHERE type_id = $1 AND ($2::boolean = FALSE OR active = TRUE)
ORDER BY sort_order, name
`

type ListItemsParams struct {
	TypeID  uuid.UUID `json:"type_id"`
	Column2 bool      `json:"column_2"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems, arg.TypeID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Name,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT id, category_id, name, sort_order, active FROM types
WHERE category_id = $1 AND ($2::boolean = FALSE OR active = TRUE)
ORDER BY sort_order, name
`

type ListTypesParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Column2    bool      `json:"column_2"`
}

func (q *Queries) ListTypes(ctx context.Context, arg ListTypesParams) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, listTypes, arg.CategoryID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = $2, sort_order = $3, active = $4 WHERE id = $1
`

type UpdateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Active    bool      `json:"active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET type_id = $2, name = $3, sort_order = $4, active = $5 WHERE id = $1
`

type UpdateItemParams struct {
	ID        uuid.UUID `json:"id"`
	TypeID    uuid.UUID `json:"type_id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Active    bool      `json:"active"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem,
		arg.ID,
		arg.TypeID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	return err
}

const updateType = `-- name: UpdateType :exec
UPDATE types SET category_id = $2, name = $3, sort_order = $4, active = $5 WHERE id = $1
`

type UpdateTypeParams struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Name       string    `json:"name"`
	SortOrder  int32     `json:"sort_order"`
	Active     bool      `json:"active"`
}

func (q *Queries) UpdateType(ctx context.Context, arg UpdateTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateType,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.SortOrder,
		arg.Active,
	)
	return err
}
