// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_fields.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCustomFieldAssignment = `-- name: CreateCustomFieldAssignment :one

INSERT INTO custom_field_assignments (id, field_def_id, scope_type, scope_id, sort_order, visible_on_new, required_on_new)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, field_def_id, scope_type, scope_id, sort_order, visible_on_new, required_on_new
`

type CreateCustomFieldAssignmentParams struct {
	ID            uuid.UUID `json:"id"`
	FieldDefID    uuid.UUID `json:"field_def_id"`
	ScopeType     string    `json:"scope_type"`
	ScopeID       uuid.UUID `json:"scope_id"`
	SortOrder     int32     `json:"sort_order"`
	VisibleOnNew  bool      `json:"visible_on_new"`
	RequiredOnNew bool      `json:"required_on_new"`
}

// ── Assignments ───────────────────────────────────────────────────────────────
func (q *Queries) CreateCustomFieldAssignment(ctx context.Context, arg CreateCustomFieldAssignmentParams) (CustomFieldAssignment, error) {
	row := q.db.QueryRowContext(ctx, createCustomFieldAssignment,
		arg.ID,
		arg.FieldDefID,
		arg.ScopeType,
		arg.ScopeID,
		arg.SortOrder,
		arg.VisibleOnNew,
		arg.RequiredOnNew,
	)
	var i CustomFieldAssignment
	err := row.Scan(
		&i.ID,
		&i.FieldDefID,
		&i.ScopeType,
		&i.ScopeID,
		&i.SortOrder,
		&i.VisibleOnNew,
		&i.RequiredOnNew,
	)
	return i, err
}

const createCustomFieldDef = `-- name: CreateCustomFieldDef :one

INSERT INTO custom_field_defs (id, name, field_type, options, sort_order, active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, field_type, options, sort_order, active, created_at
`

type CreateCustomFieldDefParams struct {
	ID        uuid.UUID             `json:"id"`
	Name      string                `json:"name"`
	FieldType string                `json:"field_type"`
	Options   pqtype.NullRawMessage `json:"options"`
	SortOrder int32                 `json:"sort_order"`
	Active    bool                  `json:"active"`
}

// ── Field definitions ─────────────────────────────────────────────────────────
func (q *Queries) CreateCustomFieldDef(ctx context.Context, arg CreateCustomFieldDefParams) (CustomFieldDef, error) {
	row := q.db.QueryRowContext(ctx, createCustomFieldDef,
		arg.ID,
		arg.Name,
		arg.FieldType,
		arg.Options,
		arg.SortOrder,
		arg.Active,
	)
	var i CustomFieldDef
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FieldType,
		&i.Options,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomFieldAssignment = `-- name: DeleteCustomFieldAssignment :exec
DELETE FROM custom_field_assignments WHERE id = $1
`

func (q *Queries) DeleteCustomFieldAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCustomFieldAssignment, id)
	return err
}

const deleteCustomFieldValue = `-- name: DeleteCustomFieldValue :exec
DELETE FROM ticket_custom_field_values
WHERE ticket_id = $1 AND field_def_id = $2
`

type DeleteCustomFieldValueParams struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	FieldDefID uuid.UUID `json:"field_def_id"`
}

func (q *Queries) DeleteCustomFieldValue(ctx context.Context, arg DeleteCustomFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomFieldValue, arg.TicketID, arg.FieldDefID)
	return err
}

const getCustomFieldAssignment = `-- name: GetCustomFieldAssignment :one
SELECT id, field_def_id, scope_type, scope_id, sort_order, visible_on_new, required_on_new FROM custom_field_assignments WHERE id = $1
`

func (q *Queries) GetCustomFieldAssignment(ctx context.Context, id uuid.UUID) (CustomFieldAssignment, error) {
	row := q.db.QueryRowContext(ctx, getCustomFieldAssignment, id)
	var i CustomFieldAssignment
	err := row.Scan(
		&i.ID,
		&i.FieldDefID,
		&i.ScopeType,
		&i.ScopeID,
		&i.SortOrder,
		&i.VisibleOnNew,
		&i.RequiredOnNew,
	)
	return i, err
}

const getCustomFieldDef = `-- name: GetCustomFieldDef :one
SELECT id, name, field_type, options, sort_order, active, created_at FROM custom_field_defs WHERE id = $1
`

func (q *Queries) GetCustomFieldDef(ctx context.Context, id uuid.UUID) (CustomFieldDef, error) {
	row := q.db.QueryRowContext(ctx, getCustomFieldDef, id)
	var i CustomFieldDef
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FieldType,
		&i.Options,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentsForScope = `-- name: ListAssignmentsForScope :many
SELECT
    a.id,
    a.field_def_id,
    a.scope_type,
    a.scope_id,
    a.sort_order,
    a.visible_on_new,
    a.required_on_new,
    d.name       AS field_name,
    d.field_type AS field_type,
    d.options    AS field_options,
    d.active     AS field_active
FROM custom_field_assignments a
JOIN custom_field_defs d ON a.field_def_id = d.id
WHERE a.scope_type = $1 AND a.scope_id = $2
ORDER BY a.sort_order
`

type ListAssignmentsForScopeParams struct {
	ScopeType string    `json:"scope_type"`
	ScopeID   uuid.UUID `json:"scope_id"`
}

type ListAssignmentsForScopeRow struct {
	ID            uuid.UUID             `json:"id"`
	FieldDefID    uuid.UUID             `json:"field_def_id"`
	ScopeType     string                `json:"scope_type"`
	ScopeID       uuid.UUID             `json:"scope_id"`
	SortOrder     int32                 `json:"sort_order"`
	VisibleOnNew  bool                  `json:"visible_on_new"`
	RequiredOnNew bool                  `json:"required_on_new"`
	FieldName     string                `json:"field_name"`
	FieldType     string                `json:"field_type"`
	FieldOptions  pqtype.NullRawMessage `json:"field_options"`
	FieldActive   bool                  `json:"field_active"`
}

func (q *Queries) ListAssignmentsForScope(ctx context.Context, arg ListAssignmentsForScopeParams) ([]ListAssignmentsForScopeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsForScope, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsForScopeRow
	for rows.Next() {
		var i ListAssignmentsForScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldDefID,
			&i.ScopeType,
			&i.ScopeID,
			&i.SortOrder,
			&i.VisibleOnNew,
			&i.RequiredOnNew,
			&i.FieldName,
			&i.FieldType,
			&i.FieldOptions,
			&i.FieldActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFieldDefs = `-- name: ListCustomFieldDefs :many
SELECT id, name, field_type, options, sort_order, active, created_at FROM custom_field_defs ORDER BY sort_order, name
`

func (q *Queries) ListCustomFieldDefs(ctx context.Context) ([]CustomFieldDef, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFieldDefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomFieldDef
	for rows.Next() {
		var i CustomFieldDef
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FieldType,
			&i.Options,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFieldValuesForTicket = `-- name: ListCustomFieldValuesForTicket :many
SELECT
    v.ticket_id,
    v.field_def_id,
    d.name       AS field_name,
    d.field_type AS field_type,
    d.options    AS field_options,
    v.value,
    v.updated_at
FROM ticket_custom_field_values v
JOIN custom_field_defs d ON v.field_def_id = d.id
WHERE v.ticket_id = $1
ORDER BY d.sort_order, d.name
`

type ListCustomFieldValuesForTicketRow struct {
	TicketID     uuid.UUID             `json:"ticket_id"`
	FieldDefID   uuid.UUID             `json:"field_def_id"`
	FieldName    string                `json:"field_name"`
	FieldType    string                `json:"field_type"`
	FieldOptions pqtype.NullRawMessage `json:"field_options"`
	Value        string                `json:"value"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

func (q *Queries) ListCustomFieldValuesForTicket(ctx context.Context, ticketID uuid.UUID) ([]ListCustomFieldValuesForTicketRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFieldValuesForTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomFieldValuesForTicketRow
	for rows.Next() {
		var i ListCustomFieldValuesForTicketRow
		if err := rows.Scan(
			&i.TicketID,
			&i.FieldDefID,
			&i.FieldName,
			&i.FieldType,
			&i.FieldOptions,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomFieldAssignment = `-- name: UpdateCustomFieldAssignment :exec
UPDATE custom_field_assignments
SET sort_order = $2, visible_on_new = $3, required_on_new = $4
WHERE id = $1
`

type UpdateCustomFieldAssignmentParams struct {
	ID            uuid.UUID `json:"id"`
	SortOrder     int32     `json:"sort_order"`
	VisibleOnNew  bool      `json:"visible_on_new"`
	RequiredOnNew bool      `json:"required_on_new"`
}

func (q *Queries) UpdateCustomFieldAssignment(ctx context.Context, arg UpdateCustomFieldAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomFieldAssignment,
		arg.ID,
		arg.SortOrder,
		arg.VisibleOnNew,
		arg.RequiredOnNew,
	)
	return err
}

const updateCustomFieldDef = `-- name: UpdateCustomFieldDef :exec
UPDATE custom_field_defs
SET name = $2, field_type = $3, options = $4, sort_order = $5, active = $6
WHERE id = $1
`

type UpdateCustomFieldDefParams struct {
	ID        uuid.UUID             `json:"id"`
	Name      string                `json:"name"`
	FieldType string                `json:"field_type"`
	Options   pqtype.NullRawMessage `json:"options"`
	SortOrder int32                 `json:"sort_order"`
	Active    bool                  `json:"active"`
}

func (q *Queries) UpdateCustomFieldDef(ctx context.Context, arg UpdateCustomFieldDefParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomFieldDef,
		arg.ID,
		arg.Name,
		arg.FieldType,
		arg.Options,
		arg.SortOrder,
		arg.Active,
	)
	return err
}

const upsertCustomFieldValue = `-- name: UpsertCustomFieldValue :exec

INSERT INTO ticket_custom_field_values (ticket_id, field_def_id, value, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (ticket_id, field_def_id)
DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type UpsertCustomFieldValueParams struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	FieldDefID uuid.UUID `json:"field_def_id"`
	Value      string    `json:"value"`
}

// ── Values ────────────────────────────────────────────────────────────────────
func (q *Queries) UpsertCustomFieldValue(ctx context.Context, arg UpsertCustomFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertCustomFieldValue, arg.TicketID, arg.FieldDefID, arg.Value)
	return err
}
