// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const addGroupScope = `-- name: AddGroupScope :exec
INSERT INTO group_scopes (group_id, category_id, type_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddGroupScopeParams struct {
	GroupID    uuid.UUID     `json:"group_id"`
	CategoryID uuid.UUID     `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
}

func (q *Queries) AddGroupScope(ctx context.Context, arg AddGroupScopeParams) error {
	_, err := q.db.ExecContext(ctx, addGroupScope, arg.GroupID, arg.CategoryID, arg.TypeID)
	return err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (id, name, description) VALUES ($1, $2, $3)
`

type CreateGroupParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup, arg.ID, arg.Name, arg.Description)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT user_id FROM group_members WHERE group_id = $1
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupScopes = `-- name: ListGroupScopes :many
SELECT group_id, category_id, type_id FROM group_scopes WHERE group_id = $1
`

func (q *Queries) ListGroupScopes(ctx context.Context, groupID uuid.UUID) ([]GroupScope, error) {
	rows, err := q.db.QueryContext(ctx, listGroupScopes, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupScope
	for rows.Next() {
		var i GroupScope
		if err := rows.Scan(&i.GroupID, &i.CategoryID, &i.TypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description FROM groups ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForExactScope = `-- name: ListGroupsForExactScope :many
SELECT DISTINCT g.id, g.name, g.description FROM groups g
JOIN group_scopes gs ON g.id = gs.group_id
WHERE gs.category_id = $1
AND (gs.type_id = $2 OR (gs.type_id IS NULL AND $2::uuid IS NULL))
ORDER BY g.name
`

type ListGroupsForExactScopeParams struct {
	CategoryID uuid.UUID     `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
}

// Returns only groups with exactly this scope (null type = category-level, non-null = type-specific).
func (q *Queries) ListGroupsForExactScope(ctx context.Context, arg ListGroupsForExactScopeParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForExactScope, arg.CategoryID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.description FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.name
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsInScope = `-- name: ListGroupsInScope :many
SELECT DISTINCT g.id, g.name, g.description FROM groups g
JOIN group_scopes gs ON g.id = gs.group_id
WHERE gs.category_id = $1
AND (gs.type_id IS NULL OR gs.type_id = $2)
ORDER BY g.name
`

type ListGroupsInScopeParams struct {
	CategoryID uuid.UUID     `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
}

func (q *Queries) ListGroupsInScope(ctx context.Context, arg ListGroupsInScopeParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsInScope, arg.CategoryID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const removeGroupScope = `-- name: RemoveGroupScope :exec
DELETE FROM group_scopes
WHERE group_id = $1 AND category_id = $2
AND (type_id = $3 OR (type_id IS NULL AND $3::uuid IS NULL))
`

type RemoveGroupScopeParams struct {
	GroupID    uuid.UUID     `json:"group_id"`
	CategoryID uuid.UUID     `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
}

func (q *Queries) RemoveGroupScope(ctx context.Context, arg RemoveGroupScopeParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupScope, arg.GroupID, arg.CategoryID, arg.TypeID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups SET name = $2, description = $3 WHERE id = $1
`

type UpdateGroupParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	return err
}
