// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest_tokens.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

const createGuestAccessToken = `-- name: CreateGuestAccessToken :exec
INSERT INTO guest_access_tokens (id, ticket_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, now())
`

type CreateGuestAccessTokenParams struct {
	ID        uuid.UUID `json:"id"`
	TicketID  uuid.UUID `json:"ticket_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateGuestAccessToken(ctx context.Context, arg CreateGuestAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, createGuestAccessToken,
		arg.ID,
		arg.TicketID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredGuestAccessTokens = `-- name: DeleteExpiredGuestAccessTokens :exec
DELETE FROM guest_access_tokens WHERE expires_at <= clock_timestamp()
`

func (q *Queries) DeleteExpiredGuestAccessTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredGuestAccessTokens)
	return err
}

const deleteGuestAccessTokensForTicket = `-- name: DeleteGuestAccessTokensForTicket :exec
DELETE FROM guest_access_tokens WHERE ticket_id = $1
`

// Rotation and revocation are the same operation: remove what the ticket has.
// Rotation then inserts a replacement in the same transaction; revocation
// does not.
func (q *Queries) DeleteGuestAccessTokensForTicket(ctx context.Context, ticketID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGuestAccessTokensForTicket, ticketID)
	return err
}

const getTicketByGuestToken = `-- name: GetTicketByGuestToken :one
SELECT t.id, t.tracking_number, t.subject, t.description, t.category_id, t.type_id,
       t.item_id, t.priority, t.status_id, t.assignee_user_id, t.assignee_group_id,
       t.reporter_user_id, t.guest_email, t.resolution_notes, t.resolved_at,
       t.closed_at, t.created_at, t.updated_at, t.guest_name, t.guest_phone
FROM guest_access_tokens g
JOIN tickets t ON t.id = g.ticket_id
WHERE g.token_hash = $1
  AND g.expires_at > clock_timestamp()
  AND t.closed_at IS NULL
`

type GetTicketByGuestTokenRow struct {
	ID              uuid.UUID      `json:"id"`
	TrackingNumber  string         `json:"tracking_number"`
	Subject         string         `json:"subject"`
	Description     string         `json:"description"`
	CategoryID      uuid.UUID      `json:"category_id"`
	TypeID          uuid.NullUUID  `json:"type_id"`
	ItemID          uuid.NullUUID  `json:"item_id"`
	Priority        string         `json:"priority"`
	StatusID        uuid.UUID      `json:"status_id"`
	AssigneeUserID  uuid.NullUUID  `json:"assignee_user_id"`
	AssigneeGroupID uuid.NullUUID  `json:"assignee_group_id"`
	ReporterUserID  uuid.NullUUID  `json:"reporter_user_id"`
	GuestEmail      sql.NullString `json:"guest_email"`
	ResolutionNotes sql.NullString `json:"resolution_notes"`
	ResolvedAt      sql.NullTime   `json:"resolved_at"`
	ClosedAt        sql.NullTime   `json:"closed_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	GuestName       string         `json:"guest_name"`
	GuestPhone      string         `json:"guest_phone"`
}

// Resolves a raw token's hash to the ticket it names, in one round trip.
//
// Expiry is decided here rather than in Go so that an expired token behaves
// exactly like a missing one — the row simply does not load, and there is no
// branch in the caller that could answer 403 and confirm the token was real.
// clock_timestamp() rather than now() for the same reason as sessions: now()
// is the transaction's start time, so two clocks were deciding one lifetime.
//
// Closed tickets are excluded: closing revokes access, and doing it in the
// query means a token that outlived its DELETE by a moment still reaches
// nothing.
// The explicit column list, not sqlc.embed: tickets carries a search_vector
// that no caller wants and that has no Go type worth naming. This is the same
// list GetTicketByID selects, so both map through one row shape.
func (q *Queries) GetTicketByGuestToken(ctx context.Context, tokenHash string) (GetTicketByGuestTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketByGuestToken, tokenHash)
	var i GetTicketByGuestTokenRow
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.Subject,
		&i.Description,
		&i.CategoryID,
		&i.TypeID,
		&i.ItemID,
		&i.Priority,
		&i.StatusID,
		&i.AssigneeUserID,
		&i.AssigneeGroupID,
		&i.ReporterUserID,
		&i.GuestEmail,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuestName,
		&i.GuestPhone,
	)
	return i, err
}

const getTicketIDByTrackingAndGuestEmail = `-- name: GetTicketIDByTrackingAndGuestEmail :one
SELECT id FROM tickets
WHERE tracking_number = $1
  AND guest_email IS NOT NULL
  AND lower(guest_email) = lower($2)
  AND closed_at IS NULL
`

type GetTicketIDByTrackingAndGuestEmailParams struct {
	TrackingNumber string `json:"tracking_number"`
	Lower          string `json:"lower"`
}

// Backs the re-request flow. Matching on both the tracking number and the
// address means possession of one alone proves nothing, and the caller
// answers 202 either way so this cannot be used to test whether either
// exists.
//
// Closed tickets are excluded so a re-request cannot resurrect access that
// closing revoked.
func (q *Queries) GetTicketIDByTrackingAndGuestEmail(ctx context.Context, arg GetTicketIDByTrackingAndGuestEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getTicketIDByTrackingAndGuestEmail, arg.TrackingNumber, arg.Lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const touchGuestAccessToken = `-- name: TouchGuestAccessToken :exec
UPDATE guest_access_tokens SET last_used_at = now()
WHERE token_hash = $1 AND last_used_at IS NULL
`

// First use stamps the row. Separate from the lookup so a read of the ticket
// is not also a write on the hot path when the column is already set.
func (q *Queries) TouchGuestAccessToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, touchGuestAccessToken, tokenHash)
	return err
}
