// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE notification_outbox
SET claimed_until = now() + make_interval(secs => $1::int),
    attempts = attempts + 1
WHERE id IN (
    SELECT id FROM notification_outbox
    WHERE failed_at IS NULL
      AND available_at <= now()
      AND (claimed_until IS NULL OR claimed_until < now())
    ORDER BY available_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, channel, event, attempts
`

type ClaimNotificationsParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	PageLimit    int32 `json:"page_limit"`
}

type ClaimNotificationsRow struct {
	ID       uuid.UUID       `json:"id"`
	Channel  string          `json:"channel"`
	Event    json.RawMessage `json:"event"`
	Attempts int32           `json:"attempts"`
}

// Takes up to page_limit due rows for this worker. SKIP LOCKED lets several
// replicas claim at once without two taking the same row; the lease
// (claimed_until) returns a row to the pool if its worker dies mid-send.
// attempts counts the claim, so a row that crashes its worker every time
// still runs out of attempts.
func (q *Queries) ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) ([]ClaimNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimNotifications, arg.LeaseSeconds, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationsRow
	for rows.Next() {
		var i ClaimNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Event,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFailedNotificationsBefore = `-- name: DeleteFailedNotificationsBefore :execrows
DELETE FROM notification_outbox WHERE failed_at < $1
`

func (q *Queries) DeleteFailedNotificationsBefore(ctx context.Context, failedAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFailedNotificationsBefore, failedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notification_outbox WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notification_outbox (id, channel, event) VALUES ($1, $2, $3)
`

type EnqueueNotificationParams struct {
	ID      uuid.UUID       `json:"id"`
	Channel string          `json:"channel"`
	Event   json.RawMessage `json:"event"`
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.ExecContext(ctx, enqueueNotification, arg.ID, arg.Channel, arg.Event)
	return err
}

const failNotification = `-- name: FailNotification :exec
UPDATE notification_outbox
SET failed_at = now(), last_error = $2, claimed_until = NULL
WHERE id = $1
`

type FailNotificationParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) FailNotification(ctx context.Context, arg FailNotificationParams) error {
	_, err := q.db.ExecContext(ctx, failNotification, arg.ID, arg.LastError)
	return err
}

const retryNotification = `-- name: RetryNotification :exec
UPDATE notification_outbox
SET available_at = $2, last_error = $3, claimed_until = NULL
WHERE id = $1
`

type RetryNotificationParams struct {
	ID          uuid.UUID      `json:"id"`
	AvailableAt time.Time      `json:"available_at"`
	LastError   sql.NullString `json:"last_error"`
}

func (q *Queries) RetryNotification(ctx context.Context, arg RetryNotificationParams) error {
	_, err := q.db.ExecContext(ctx, retryNotification, arg.ID, arg.AvailableAt, arg.LastError)
	return err
}
