// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_registrations.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const deletePendingRegistration = `-- name: DeletePendingRegistration :exec
DELETE FROM pending_registrations WHERE id = $1
`

func (q *Queries) DeletePendingRegistration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePendingRegistration, id)
	return err
}

const getPendingRegistrationByToken = `-- name: GetPendingRegistrationByToken :one
SELECT id, email, display_name, password_hash, token, expires_at, created_at FROM pending_registrations WHERE token = $1
`

func (q *Queries) GetPendingRegistrationByToken(ctx context.Context, token uuid.UUID) (PendingRegistration, error) {
	row := q.db.QueryRowContext(ctx, getPendingRegistrationByToken, token)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPendingRegistration = `-- name: UpsertPendingRegistration :one
INSERT INTO pending_registrations (id, email, display_name, password_hash, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (lower(email)) DO UPDATE
    SET display_name  = EXCLUDED.display_name,
        password_hash = EXCLUDED.password_hash,
        token         = EXCLUDED.token,
        expires_at    = EXCLUDED.expires_at,
        created_at    = EXCLUDED.created_at
RETURNING id, email, display_name, password_hash, token, expires_at, created_at
`

type UpsertPendingRegistrationParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Token        uuid.UUID `json:"token"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) UpsertPendingRegistration(ctx context.Context, arg UpsertPendingRegistrationParams) (PendingRegistration, error) {
	row := q.db.QueryRowContext(ctx, upsertPendingRegistration,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
