// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package dbgen

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createPlugin = `-- name: CreatePlugin :exec
INSERT INTO plugins (id, name, version, description, author, runtime, hooks, enabled, wasm_path, installed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreatePluginParams struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Version     string    `json:"version"`
	Description string    `json:"description"`
	Author      string    `json:"author"`
	Runtime     string    `json:"runtime"`
	Hooks       []string  `json:"hooks"`
	Enabled     bool      `json:"enabled"`
	WasmPath    string    `json:"wasm_path"`
	InstalledAt time.Time `json:"installed_at"`
}

func (q *Queries) CreatePlugin(ctx context.Context, arg CreatePluginParams) error {
	_, err := q.db.ExecContext(ctx, createPlugin,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Author,
		arg.Runtime,
		pq.Array(arg.Hooks),
		arg.Enabled,
		arg.WasmPath,
		arg.InstalledAt,
	)
	return err
}

const deletePlugin = `-- name: DeletePlugin :exec
DELETE FROM plugins WHERE id = $1
`

func (q *Queries) DeletePlugin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlugin, id)
	return err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, name, version, description, author, runtime, hooks, enabled, wasm_path, installed_at FROM plugins WHERE id = $1
`

func (q *Queries) GetPlugin(ctx context.Context, id string) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Author,
		&i.Runtime,
		pq.Array(&i.Hooks),
		&i.Enabled,
		&i.WasmPath,
		&i.InstalledAt,
	)
	return i, err
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, name, version, description, author, runtime, hooks, enabled, wasm_path, installed_at FROM plugins ORDER BY name
`

func (q *Queries) ListPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Author,
			&i.Runtime,
			pq.Array(&i.Hooks),
			&i.Enabled,
			&i.WasmPath,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlugin = `-- name: UpdatePlugin :exec
UPDATE plugins SET name = $2, version = $3, enabled = $4, wasm_path = $5 WHERE id = $1
`

type UpdatePluginParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Version  string `json:"version"`
	Enabled  bool   `json:"enabled"`
	WasmPath string `json:"wasm_path"`
}

func (q *Queries) UpdatePlugin(ctx context.Context, arg UpdatePluginParams) error {
	_, err := q.db.ExecContext(ctx, updatePlugin,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Enabled,
		arg.WasmPath,
	)
	return err
}
