// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

// Every session a user holds. Used for disable, role change, password change
// and MFA reset — the events after which a cookie minted under the old state
// must stop working.
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.data, s.expires_at, s.created_at, s.updated_at FROM sessions s
LEFT JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.expires_at > now()
  AND (s.user_id IS NULL OR (u.disabled = FALSE AND u.deleted_at IS NULL))
`

type GetSessionRow struct {
	Session Session `json:"session"`
}

// Only unexpired rows: an expired session must behave exactly like a missing
// one, so a stale row cannot authenticate anybody between sweeps.
//
// The join makes a disabled or deleted user's session behave the same way.
// Disabling already deletes a user's sessions, but that is a write racing the
// login it is meant to stop: a disable landing between the password check and
// the session INSERT deleted nothing and left a live session behind. Deciding
// it here instead means there is no window to lose — the row simply does not
// load. This costs no extra round trip, since the session lookup already
// queries the database on every authenticated request.
//
// LEFT JOIN, and user_id IS NULL passes: the OIDC flow writes state (nonce,
// PKCE verifier) into a session before anybody has authenticated, and an inner
// join would drop those and break the login it is protecting.
func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.Data,
		&i.Session.ExpiresAt,
		&i.Session.CreatedAt,
		&i.Session.UpdatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, user_id, data, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET user_id    = EXCLUDED.user_id,
    data       = EXCLUDED.data,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
`

type UpsertSessionParams struct {
	ID        string        `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Data      []byte        `json:"data"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.UserID,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}
