// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sla.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
	"github.com/lib/pq"
)

const createSLAPolicy = `-- name: CreateSLAPolicy :exec
INSERT INTO sla_policies (id, name, priority, category_id, response_target_min, resolution_target_min)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSLAPolicyParams struct {
	ID                  uuid.UUID      `json:"id"`
	Name                string         `json:"name"`
	Priority            sql.NullString `json:"priority"`
	CategoryID          uuid.NullUUID  `json:"category_id"`
	ResponseTargetMin   int32          `json:"response_target_min"`
	ResolutionTargetMin int32          `json:"resolution_target_min"`
}

func (q *Queries) CreateSLAPolicy(ctx context.Context, arg CreateSLAPolicyParams) error {
	_, err := q.db.ExecContext(ctx, createSLAPolicy,
		arg.ID,
		arg.Name,
		arg.Priority,
		arg.CategoryID,
		arg.ResponseTargetMin,
		arg.ResolutionTargetMin,
	)
	return err
}

const createSLARecord = `-- name: CreateSLARecord :exec
INSERT INTO sla_records (ticket_id, policy_id, first_response_at, resolved_at, response_breached_at, resolution_breached_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSLARecordParams struct {
	TicketID             uuid.UUID    `json:"ticket_id"`
	PolicyID             uuid.UUID    `json:"policy_id"`
	FirstResponseAt      sql.NullTime `json:"first_response_at"`
	ResolvedAt           sql.NullTime `json:"resolved_at"`
	ResponseBreachedAt   sql.NullTime `json:"response_breached_at"`
	ResolutionBreachedAt sql.NullTime `json:"resolution_breached_at"`
}

func (q *Queries) CreateSLARecord(ctx context.Context, arg CreateSLARecordParams) error {
	_, err := q.db.ExecContext(ctx, createSLARecord,
		arg.TicketID,
		arg.PolicyID,
		arg.FirstResponseAt,
		arg.ResolvedAt,
		arg.ResponseBreachedAt,
		arg.ResolutionBreachedAt,
	)
	return err
}

const deleteSLAPolicy = `-- name: DeleteSLAPolicy :exec
DELETE FROM sla_policies WHERE id = $1
`

func (q *Queries) DeleteSLAPolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSLAPolicy, id)
	return err
}

const findSLAPolicy = `-- name: FindSLAPolicy :one
SELECT id, name, priority, category_id, response_target_min, resolution_target_min FROM sla_policies
WHERE (priority IS NULL OR priority = $1::text)
  AND (category_id IS NULL OR category_id = $2::uuid)
ORDER BY
  CASE
    WHEN priority IS NOT NULL AND category_id IS NOT NULL THEN 1
    WHEN priority IS NOT NULL THEN 2
    WHEN category_id IS NOT NULL THEN 3
    ELSE 4
  END
LIMIT 1
`

type FindSLAPolicyParams struct {
	Priority   string    `json:"priority"`
	CategoryID uuid.UUID `json:"category_id"`
}

// The four tiers DESIGN.md documents, most specific first:
//  1. Priority + Category
//  2. Priority only      (category_id IS NULL = any category)
//  3. Category only      (priority IS NULL = any priority)
//  4. Catch-all          (neither set)
//
// A NULL column means "matches anything", so the WHERE admits every candidate
// and the ORDER BY picks the most specific. Before this, priority was NOT NULL
// and the predicate required an exact match, so tiers 3 and 4 could neither be
// stored nor matched.
func (q *Queries) FindSLAPolicy(ctx context.Context, arg FindSLAPolicyParams) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, findSLAPolicy, arg.Priority, arg.CategoryID)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.CategoryID,
		&i.ResponseTargetMin,
		&i.ResolutionTargetMin,
	)
	return i, err
}

const getSLAPolicy = `-- name: GetSLAPolicy :one
SELECT id, name, priority, category_id, response_target_min, resolution_target_min FROM sla_policies WHERE id = $1
`

func (q *Queries) GetSLAPolicy(ctx context.Context, id uuid.UUID) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, getSLAPolicy, id)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.CategoryID,
		&i.ResponseTargetMin,
		&i.ResolutionTargetMin,
	)
	return i, err
}

const getSLARecord = `-- name: GetSLARecord :one
SELECT ticket_id, policy_id, first_response_at, resolved_at, response_breached_at, resolution_breached_at, response_elapsed_at_met_seconds, resolution_elapsed_at_met_seconds FROM sla_records WHERE ticket_id = $1
`

func (q *Queries) GetSLARecord(ctx context.Context, ticketID uuid.UUID) (SlaRecord, error) {
	row := q.db.QueryRowContext(ctx, getSLARecord, ticketID)
	var i SlaRecord
	err := row.Scan(
		&i.TicketID,
		&i.PolicyID,
		&i.FirstResponseAt,
		&i.ResolvedAt,
		&i.ResponseBreachedAt,
		&i.ResolutionBreachedAt,
		&i.ResponseElapsedAtMetSeconds,
		&i.ResolutionElapsedAtMetSeconds,
	)
	return i, err
}

const listSLABreachCandidates = `-- name: ListSLABreachCandidates :many
SELECT r.ticket_id
FROM sla_records r
JOIN tickets      t ON t.id = r.ticket_id
JOIN sla_policies p ON p.id = r.policy_id
WHERE t.closed_at IS NULL
  AND (
       (r.first_response_at IS NULL AND r.response_breached_at IS NULL
          AND t.created_at
              + make_interval(secs => t.sla_paused_seconds::double precision)
              + make_interval(mins => p.response_target_min)
              <= LEAST(COALESCE(t.pending_since, $1::timestamptz), $1::timestamptz))
    OR (r.resolved_at IS NULL AND r.resolution_breached_at IS NULL
          AND t.created_at
              + make_interval(secs => t.sla_paused_seconds::double precision)
              + make_interval(mins => p.resolution_target_min)
              <= LEAST(COALESCE(t.pending_since, $1::timestamptz), $1::timestamptz))
  )
ORDER BY t.created_at
`

// Tickets the breach sweep must evaluate: open, under a policy, with at least
// one target that is neither met nor already stamped, using the same
// pause-aware elapsed time as sla.Elapsed (see that function's doc comment;
// the two must change together). LEAST(COALESCE(pending_since, now), now) is
// the instant the SLA clock stopped: pending_since while the ticket is
// currently Pending, clipped to now the same way Elapsed clips with
// at.After(*PendingSince), and now otherwise. A Pending ticket whose frozen
// elapsed time is still under target is therefore never selected. This
// prefilter must still return everything EvaluateBreaches would stamp — it
// stays a superset via <=, where Go's strict > decides the exact equality
// instant on a fresh read of the row — see
// TestSLAStore_ListBreachCandidates's superset invariant check.
func (q *Queries) ListSLABreachCandidates(ctx context.Context, now time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listSLABreachCandidates, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var ticket_id uuid.UUID
		if err := rows.Scan(&ticket_id); err != nil {
			return nil, err
		}
		items = append(items, ticket_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLAPolicies = `-- name: ListSLAPolicies :many
SELECT id, name, priority, category_id, response_target_min, resolution_target_min FROM sla_policies ORDER BY priority, name
`

func (q *Queries) ListSLAPolicies(ctx context.Context) ([]SlaPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listSLAPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaPolicy
	for rows.Next() {
		var i SlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.CategoryID,
			&i.ResponseTargetMin,
			&i.ResolutionTargetMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSLARecordsByTicketIDs = `-- name: ListSLARecordsByTicketIDs :many
SELECT ticket_id, policy_id, first_response_at, resolved_at, response_breached_at, resolution_breached_at, response_elapsed_at_met_seconds, resolution_elapsed_at_met_seconds FROM sla_records WHERE ticket_id = ANY($1::uuid[])
`

// Batch lookup for the per-ticket SLA status embedded on GET /tickets and
// GET /tickets/{id} (#183): one query for the whole page, after it is
// sliced, rather than a JOIN pushed into every one of the ~12 list/search
// queries that would compute SLA for limit×(1+groups) rows and throw most
// of them away. See sla.Service.StatusesFor.
func (q *Queries) ListSLARecordsByTicketIDs(ctx context.Context, ticketIds []uuid.UUID) ([]SlaRecord, error) {
	rows, err := q.db.QueryContext(ctx, listSLARecordsByTicketIDs, pq.Array(ticketIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaRecord
	for rows.Next() {
		var i SlaRecord
		if err := rows.Scan(
			&i.TicketID,
			&i.PolicyID,
			&i.FirstResponseAt,
			&i.ResolvedAt,
			&i.ResponseBreachedAt,
			&i.ResolutionBreachedAt,
			&i.ResponseElapsedAtMetSeconds,
			&i.ResolutionElapsedAtMetSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSLAFirstResponse = `-- name: SetSLAFirstResponse :exec
UPDATE sla_records
SET first_response_at = COALESCE(first_response_at, $2::timestamptz),
    response_elapsed_at_met_seconds = COALESCE(response_elapsed_at_met_seconds, $3::bigint),
    response_breached_at = CASE
        WHEN first_response_at IS NULL
             AND $3::bigint > $4::bigint
            THEN COALESCE(response_breached_at, $2::timestamptz)
        ELSE response_breached_at
    END
WHERE ticket_id = $1
`

type SetSLAFirstResponseParams struct {
	TicketID              uuid.UUID `json:"ticket_id"`
	At                    time.Time `json:"at"`
	ElapsedSeconds        int64     `json:"elapsed_seconds"`
	ResponseTargetSeconds int64     `json:"response_target_seconds"`
}

// Marks the first response, freezes elapsed-toward-target as of that same
// moment, AND stamps a response breach if it is already late — all in ONE
// statement. COALESCE-guarded like StampSLABreaches below: it only ever
// writes first_response_at / response_elapsed_at_met_seconds /
// response_breached_at, and only while each is still NULL, so it cannot race
// with StampSLABreaches clobbering a breach stamp the way a full-row
// UpdateSLARecord read-then-write could (see CLAUDE.md). Idempotent for the
// same reason: a retried call finds every column already set and changes
// nothing.
//
// #228: this used to be the fact write alone, with the caller separately
// reading the record, deciding whether to breach from that (possibly stale)
// read, and issuing a second StampSLABreaches statement. Two consequences:
// two near-simultaneous calls could both decide from a stale pre-write read,
// so the LOSING call's own (later, larger) elapsed reading could still land
// a breach stamp even though the WINNING call's earlier, on-time write is
// what actually took — a stray, uncleared breach stamp next to a frozen
// green elapsed reading. And a failure between the fact write and the
// now-separate breach-stamp statement could lose a genuine late-response
// signal permanently (ListSLABreachCandidates excludes a ticket once
// first_response_at is set, so nothing ever revisits it).
//
// Folding both into one statement removes the gap entirely: every column
// reference on the right of "=" reads this row as it stood BEFORE this
// statement (a single UPDATE's SET list is computed once, from the pre-image
// row, never from another SET clause's new value), so
// "first_response_at IS NULL" means "nothing has won this race yet — THIS
// call's write is the one that lands, and its own elapsed reading is the one
// the breach decision is made from." A losing call (first_response_at
// already NOT NULL) touches nothing at all, including response_breached_at,
// so it can never stamp a breach the winning call did not itself decide.
func (q *Queries) SetSLAFirstResponse(ctx context.Context, arg SetSLAFirstResponseParams) error {
	_, err := q.db.ExecContext(ctx, setSLAFirstResponse,
		arg.TicketID,
		arg.At,
		arg.ElapsedSeconds,
		arg.ResponseTargetSeconds,
	)
	return err
}

const setSLAResolved = `-- name: SetSLAResolved :exec
UPDATE sla_records
SET resolved_at = COALESCE(resolved_at, $2::timestamptz),
    resolution_elapsed_at_met_seconds = COALESCE(resolution_elapsed_at_met_seconds, $3::bigint),
    resolution_breached_at = CASE
        WHEN resolved_at IS NULL
             AND $3::bigint > $4::bigint
            THEN COALESCE(resolution_breached_at, $2::timestamptz)
        ELSE resolution_breached_at
    END
WHERE ticket_id = $1
`

type SetSLAResolvedParams struct {
	TicketID                uuid.UUID `json:"ticket_id"`
	At                      time.Time `json:"at"`
	ElapsedSeconds          int64     `json:"elapsed_seconds"`
	ResolutionTargetSeconds int64     `json:"resolution_target_seconds"`
}

// The resolution-side twin of SetSLAFirstResponse: see its comment for why
// the fact write and the breach stamp are one statement (#228), and why
// every right-hand-side column reference here reads the PRE-UPDATE row.
func (q *Queries) SetSLAResolved(ctx context.Context, arg SetSLAResolvedParams) error {
	_, err := q.db.ExecContext(ctx, setSLAResolved,
		arg.TicketID,
		arg.At,
		arg.ElapsedSeconds,
		arg.ResolutionTargetSeconds,
	)
	return err
}

const stampSLABreaches = `-- name: StampSLABreaches :exec
UPDATE sla_records
SET response_breached_at   = COALESCE(response_breached_at,   $2::timestamptz),
    resolution_breached_at = COALESCE(resolution_breached_at, $3::timestamptz)
WHERE ticket_id = $1
`

type StampSLABreachesParams struct {
	TicketID             uuid.UUID    `json:"ticket_id"`
	ResponseBreachedAt   sql.NullTime `json:"response_breached_at"`
	ResolutionBreachedAt sql.NullTime `json:"resolution_breached_at"`
}

// Sets only the breach columns, and only where still NULL. Two evaluators
// racing on the same row cannot overwrite each other's stamp or, worse, the
// request path's first_response_at / resolved_at. A stamp, once set, is a
// fact about what happened (DESIGN.md) and is never cleared here.
func (q *Queries) StampSLABreaches(ctx context.Context, arg StampSLABreachesParams) error {
	_, err := q.db.ExecContext(ctx, stampSLABreaches, arg.TicketID, arg.ResponseBreachedAt, arg.ResolutionBreachedAt)
	return err
}

const updateSLAPolicy = `-- name: UpdateSLAPolicy :exec
UPDATE sla_policies
SET name = $2, priority = $3, category_id = $4,
    response_target_min = $5, resolution_target_min = $6
WHERE id = $1
`

type UpdateSLAPolicyParams struct {
	ID                  uuid.UUID      `json:"id"`
	Name                string         `json:"name"`
	Priority            sql.NullString `json:"priority"`
	CategoryID          uuid.NullUUID  `json:"category_id"`
	ResponseTargetMin   int32          `json:"response_target_min"`
	ResolutionTargetMin int32          `json:"resolution_target_min"`
}

func (q *Queries) UpdateSLAPolicy(ctx context.Context, arg UpdateSLAPolicyParams) error {
	_, err := q.db.ExecContext(ctx, updateSLAPolicy,
		arg.ID,
		arg.Name,
		arg.Priority,
		arg.CategoryID,
		arg.ResponseTargetMin,
		arg.ResolutionTargetMin,
	)
	return err
}

const updateSLARecord = `-- name: UpdateSLARecord :exec
UPDATE sla_records
SET first_response_at = $2, resolved_at = $3,
    response_breached_at = $4, resolution_breached_at = $5
WHERE ticket_id = $1
`

type UpdateSLARecordParams struct {
	TicketID             uuid.UUID    `json:"ticket_id"`
	FirstResponseAt      sql.NullTime `json:"first_response_at"`
	ResolvedAt           sql.NullTime `json:"resolved_at"`
	ResponseBreachedAt   sql.NullTime `json:"response_breached_at"`
	ResolutionBreachedAt sql.NullTime `json:"resolution_breached_at"`
}

func (q *Queries) UpdateSLARecord(ctx context.Context, arg UpdateSLARecordParams) error {
	_, err := q.db.ExecContext(ctx, updateSLARecord,
		arg.TicketID,
		arg.FirstResponseAt,
		arg.ResolvedAt,
		arg.ResponseBreachedAt,
		arg.ResolutionBreachedAt,
	)
	return err
}
