// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sla.sql

package dbgen

import (
	"context"
	"database/sql"

	uuid "github.com/google/uuid"
)

const createSLAPolicy = `-- name: CreateSLAPolicy :exec
INSERT INTO sla_policies (id, name, priority, category_id, response_target_min, resolution_target_min)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSLAPolicyParams struct {
	ID                  uuid.UUID     `json:"id"`
	Name                string        `json:"name"`
	Priority            string        `json:"priority"`
	CategoryID          uuid.NullUUID `json:"category_id"`
	ResponseTargetMin   int32         `json:"response_target_min"`
	ResolutionTargetMin int32         `json:"resolution_target_min"`
}

func (q *Queries) CreateSLAPolicy(ctx context.Context, arg CreateSLAPolicyParams) error {
	_, err := q.db.ExecContext(ctx, createSLAPolicy,
		arg.ID,
		arg.Name,
		arg.Priority,
		arg.CategoryID,
		arg.ResponseTargetMin,
		arg.ResolutionTargetMin,
	)
	return err
}

const createSLARecord = `-- name: CreateSLARecord :exec
INSERT INTO sla_records (ticket_id, policy_id, first_response_at, resolved_at, response_breached_at, resolution_breached_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSLARecordParams struct {
	TicketID             uuid.UUID    `json:"ticket_id"`
	PolicyID             uuid.UUID    `json:"policy_id"`
	FirstResponseAt      sql.NullTime `json:"first_response_at"`
	ResolvedAt           sql.NullTime `json:"resolved_at"`
	ResponseBreachedAt   sql.NullTime `json:"response_breached_at"`
	ResolutionBreachedAt sql.NullTime `json:"resolution_breached_at"`
}

func (q *Queries) CreateSLARecord(ctx context.Context, arg CreateSLARecordParams) error {
	_, err := q.db.ExecContext(ctx, createSLARecord,
		arg.TicketID,
		arg.PolicyID,
		arg.FirstResponseAt,
		arg.ResolvedAt,
		arg.ResponseBreachedAt,
		arg.ResolutionBreachedAt,
	)
	return err
}

const deleteSLAPolicy = `-- name: DeleteSLAPolicy :exec
DELETE FROM sla_policies WHERE id = $1
`

func (q *Queries) DeleteSLAPolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSLAPolicy, id)
	return err
}

const findSLAPolicy = `-- name: FindSLAPolicy :one
SELECT id, name, priority, category_id, response_target_min, resolution_target_min FROM sla_policies
WHERE priority = $1
  AND (category_id = $2 OR category_id IS NULL)
ORDER BY category_id NULLS LAST
LIMIT 1
`

type FindSLAPolicyParams struct {
	Priority   string        `json:"priority"`
	CategoryID uuid.NullUUID `json:"category_id"`
}

// Category-specific policy takes precedence over a global one (category_id IS NULL).
func (q *Queries) FindSLAPolicy(ctx context.Context, arg FindSLAPolicyParams) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, findSLAPolicy, arg.Priority, arg.CategoryID)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.CategoryID,
		&i.ResponseTargetMin,
		&i.ResolutionTargetMin,
	)
	return i, err
}

const getSLAPolicy = `-- name: GetSLAPolicy :one
SELECT id, name, priority, category_id, response_target_min, resolution_target_min FROM sla_policies WHERE id = $1
`

func (q *Queries) GetSLAPolicy(ctx context.Context, id uuid.UUID) (SlaPolicy, error) {
	row := q.db.QueryRowContext(ctx, getSLAPolicy, id)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.CategoryID,
		&i.ResponseTargetMin,
		&i.ResolutionTargetMin,
	)
	return i, err
}

const getSLARecord = `-- name: GetSLARecord :one
SELECT ticket_id, policy_id, first_response_at, resolved_at, response_breached_at, resolution_breached_at FROM sla_records WHERE ticket_id = $1
`

func (q *Queries) GetSLARecord(ctx context.Context, ticketID uuid.UUID) (SlaRecord, error) {
	row := q.db.QueryRowContext(ctx, getSLARecord, ticketID)
	var i SlaRecord
	err := row.Scan(
		&i.TicketID,
		&i.PolicyID,
		&i.FirstResponseAt,
		&i.ResolvedAt,
		&i.ResponseBreachedAt,
		&i.ResolutionBreachedAt,
	)
	return i, err
}

const listSLAPolicies = `-- name: ListSLAPolicies :many
SELECT id, name, priority, category_id, response_target_min, resolution_target_min FROM sla_policies ORDER BY priority, name
`

func (q *Queries) ListSLAPolicies(ctx context.Context) ([]SlaPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listSLAPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaPolicy
	for rows.Next() {
		var i SlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.CategoryID,
			&i.ResponseTargetMin,
			&i.ResolutionTargetMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSLAPolicy = `-- name: UpdateSLAPolicy :exec
UPDATE sla_policies
SET name = $2, priority = $3, category_id = $4,
    response_target_min = $5, resolution_target_min = $6
WHERE id = $1
`

type UpdateSLAPolicyParams struct {
	ID                  uuid.UUID     `json:"id"`
	Name                string        `json:"name"`
	Priority            string        `json:"priority"`
	CategoryID          uuid.NullUUID `json:"category_id"`
	ResponseTargetMin   int32         `json:"response_target_min"`
	ResolutionTargetMin int32         `json:"resolution_target_min"`
}

func (q *Queries) UpdateSLAPolicy(ctx context.Context, arg UpdateSLAPolicyParams) error {
	_, err := q.db.ExecContext(ctx, updateSLAPolicy,
		arg.ID,
		arg.Name,
		arg.Priority,
		arg.CategoryID,
		arg.ResponseTargetMin,
		arg.ResolutionTargetMin,
	)
	return err
}

const updateSLARecord = `-- name: UpdateSLARecord :exec
UPDATE sla_records
SET first_response_at = $2, resolved_at = $3,
    response_breached_at = $4, resolution_breached_at = $5
WHERE ticket_id = $1
`

type UpdateSLARecordParams struct {
	TicketID             uuid.UUID    `json:"ticket_id"`
	FirstResponseAt      sql.NullTime `json:"first_response_at"`
	ResolvedAt           sql.NullTime `json:"resolved_at"`
	ResponseBreachedAt   sql.NullTime `json:"response_breached_at"`
	ResolutionBreachedAt sql.NullTime `json:"resolution_breached_at"`
}

func (q *Queries) UpdateSLARecord(ctx context.Context, arg UpdateSLARecordParams) error {
	_, err := q.db.ExecContext(ctx, updateSLARecord,
		arg.TicketID,
		arg.FirstResponseAt,
		arg.ResolvedAt,
		arg.ResponseBreachedAt,
		arg.ResolutionBreachedAt,
	)
	return err
}
