// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statuses.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createStatus = `-- name: CreateStatus :exec
INSERT INTO statuses (id, name, kind, sort_order, color) VALUES ($1, $2, $3, $4, $5)
`

type CreateStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	SortOrder int32     `json:"sort_order"`
	Color     string    `json:"color"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.SortOrder,
		arg.Color,
	)
	return err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM statuses WHERE id = $1 AND kind = 'custom'
`

func (q *Queries) DeleteStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStatus, id)
	return err
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, kind, sort_order, color FROM statuses WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id uuid.UUID) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.Color,
	)
	return i, err
}

const getStatusByName = `-- name: GetStatusByName :one
SELECT id, name, kind, sort_order, color FROM statuses WHERE name = $1
`

func (q *Queries) GetStatusByName(ctx context.Context, name string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByName, name)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.Color,
	)
	return i, err
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, name, kind, sort_order, color FROM statuses ORDER BY sort_order, name
`

func (q *Queries) ListStatuses(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, listStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE statuses SET name = $2, sort_order = $3, color = $4 WHERE id = $1
`

type UpdateStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Color     string    `json:"color"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.Color,
	)
	return err
}
