// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_history.sql

package dbgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createStatusHistoryEntry = `-- name: CreateStatusHistoryEntry :exec
INSERT INTO ticket_status_history (id, ticket_id, from_status_id, to_status_id, changed_by_user_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateStatusHistoryEntryParams struct {
	ID              uuid.UUID     `json:"id"`
	TicketID        uuid.UUID     `json:"ticket_id"`
	FromStatusID    uuid.NullUUID `json:"from_status_id"`
	ToStatusID      uuid.UUID     `json:"to_status_id"`
	ChangedByUserID uuid.NullUUID `json:"changed_by_user_id"`
	CreatedAt       time.Time     `json:"created_at"`
}

func (q *Queries) CreateStatusHistoryEntry(ctx context.Context, arg CreateStatusHistoryEntryParams) error {
	_, err := q.db.ExecContext(ctx, createStatusHistoryEntry,
		arg.ID,
		arg.TicketID,
		arg.FromStatusID,
		arg.ToStatusID,
		arg.ChangedByUserID,
		arg.CreatedAt,
	)
	return err
}

const listTicketStatusHistory = `-- name: ListTicketStatusHistory :many
SELECT
    h.id,
    h.ticket_id,
    h.from_status_id,
    COALESCE(s_from.name,  '') AS from_status_name,
    COALESCE(s_from.color, '') AS from_status_color,
    h.to_status_id,
    s_to.name                  AS to_status_name,
    s_to.color                 AS to_status_color,
    h.changed_by_user_id,
    COALESCE(u.display_name, '') AS changed_by_name,
    h.created_at
FROM ticket_status_history h
LEFT JOIN statuses s_from ON h.from_status_id  = s_from.id
JOIN      statuses s_to   ON h.to_status_id    = s_to.id
LEFT JOIN users    u      ON h.changed_by_user_id = u.id
WHERE h.ticket_id = $1
ORDER BY h.created_at ASC
`

type ListTicketStatusHistoryRow struct {
	ID              uuid.UUID     `json:"id"`
	TicketID        uuid.UUID     `json:"ticket_id"`
	FromStatusID    uuid.NullUUID `json:"from_status_id"`
	FromStatusName  string        `json:"from_status_name"`
	FromStatusColor string        `json:"from_status_color"`
	ToStatusID      uuid.UUID     `json:"to_status_id"`
	ToStatusName    string        `json:"to_status_name"`
	ToStatusColor   string        `json:"to_status_color"`
	ChangedByUserID uuid.NullUUID `json:"changed_by_user_id"`
	ChangedByName   string        `json:"changed_by_name"`
	CreatedAt       time.Time     `json:"created_at"`
}

func (q *Queries) ListTicketStatusHistory(ctx context.Context, ticketID uuid.UUID) ([]ListTicketStatusHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketStatusHistory, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketStatusHistoryRow
	for rows.Next() {
		var i ListTicketStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.FromStatusID,
			&i.FromStatusName,
			&i.FromStatusColor,
			&i.ToStatusID,
			&i.ToStatusName,
			&i.ToStatusColor,
			&i.ChangedByUserID,
			&i.ChangedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
