// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: statuses.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/lib/pq"
)

const countTicketsByStatus = `-- name: CountTicketsByStatus :one
SELECT COUNT(*) FROM tickets WHERE status_id = $1
`

func (q *Queries) CountTicketsByStatus(ctx context.Context, statusID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsByStatus, statusID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsByStatusForAssignee = `-- name: CountTicketsByStatusForAssignee :one
SELECT COUNT(*) FROM tickets
WHERE status_id = $1
  AND (assignee_user_id = $2 OR assignee_group_id = ANY($3::uuid[]))
`

type CountTicketsByStatusForAssigneeParams struct {
	StatusID       uuid.UUID     `json:"status_id"`
	AssigneeUserID uuid.NullUUID `json:"assignee_user_id"`
	GroupIds       []uuid.UUID   `json:"group_ids"`
}

func (q *Queries) CountTicketsByStatusForAssignee(ctx context.Context, arg CountTicketsByStatusForAssigneeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsByStatusForAssignee, arg.StatusID, arg.AssigneeUserID, pq.Array(arg.GroupIds))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsByStatusForReporter = `-- name: CountTicketsByStatusForReporter :one
SELECT COUNT(*) FROM tickets
WHERE status_id = $1 AND reporter_user_id = $2
`

type CountTicketsByStatusForReporterParams struct {
	StatusID       uuid.UUID     `json:"status_id"`
	ReporterUserID uuid.NullUUID `json:"reporter_user_id"`
}

func (q *Queries) CountTicketsByStatusForReporter(ctx context.Context, arg CountTicketsByStatusForReporterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsByStatusForReporter, arg.StatusID, arg.ReporterUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatus = `-- name: CreateStatus :exec
INSERT INTO statuses (id, name, kind, sort_order, color) VALUES ($1, $2, $3, $4, $5)
`

type CreateStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	SortOrder int32     `json:"sort_order"`
	Color     string    `json:"color"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.SortOrder,
		arg.Color,
	)
	return err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM statuses WHERE id = $1 AND kind = 'custom'
`

func (q *Queries) DeleteStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStatus, id)
	return err
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, kind, sort_order, color, active FROM statuses WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id uuid.UUID) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.Color,
		&i.Active,
	)
	return i, err
}

const getStatusByName = `-- name: GetStatusByName :one
SELECT id, name, kind, sort_order, color, active FROM statuses WHERE name = $1
`

func (q *Queries) GetStatusByName(ctx context.Context, name string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByName, name)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.Color,
		&i.Active,
	)
	return i, err
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, name, kind, sort_order, color, active FROM statuses ORDER BY sort_order, name
`

func (q *Queries) ListStatuses(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, listStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.Color,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE statuses SET name = $2, sort_order = $3, color = $4, active = $5 WHERE id = $1
`

type UpdateStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Color     string    `json:"color"`
	Active    bool      `json:"active"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.Color,
		arg.Active,
	)
	return err
}
