// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const addTicketTag = `-- name: AddTicketTag :exec
INSERT INTO ticket_tags (ticket_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTicketTagParams struct {
	TicketID uuid.UUID `json:"ticket_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTicketTag(ctx context.Context, arg AddTicketTagParams) error {
	_, err := q.db.ExecContext(ctx, addTicketTag, arg.TicketID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name) VALUES ($1) RETURNING id, name, created_at, deleted_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at, deleted_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveTags = `-- name: ListActiveTags :many
SELECT id, name, created_at, deleted_at FROM tags WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListActiveTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, created_at, deleted_at FROM tags ORDER BY name
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTags = `-- name: ListTicketTags :many
SELECT t.id, t.name, t.created_at, t.deleted_at FROM tags t
JOIN ticket_tags tt ON tt.tag_id = t.id
WHERE tt.ticket_id = $1
ORDER BY t.name
`

func (q *Queries) ListTicketTags(ctx context.Context, ticketID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTicketTags, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTicketTag = `-- name: RemoveTicketTag :exec
DELETE FROM ticket_tags WHERE ticket_id = $1 AND tag_id = $2
`

type RemoveTicketTagParams struct {
	TicketID uuid.UUID `json:"ticket_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTicketTag(ctx context.Context, arg RemoveTicketTagParams) error {
	_, err := q.db.ExecContext(ctx, removeTicketTag, arg.TicketID, arg.TagID)
	return err
}

const restoreTag = `-- name: RestoreTag :exec
UPDATE tags SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreTag, id)
	return err
}

const searchActiveTags = `-- name: SearchActiveTags :many
SELECT id, name, created_at, deleted_at FROM tags WHERE deleted_at IS NULL AND name LIKE $1 ORDER BY name LIMIT 20
`

func (q *Queries) SearchActiveTags(ctx context.Context, name string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, searchActiveTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTag, id)
	return err
}
