// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/google/uuid"
)

const adminSetPassword = `-- name: AdminSetPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type AdminSetPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) AdminSetPassword(ctx context.Context, arg AdminSetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, adminSetPassword, arg.ID, arg.PasswordHash)
	return err
}

const claimMFAAttempt = `-- name: ClaimMFAAttempt :one
UPDATE users
SET mfa_failed_attempts = CASE
        WHEN mfa_locked_until IS NOT NULL AND mfa_locked_until <= now() THEN 1
        ELSE mfa_failed_attempts + 1
    END,
    mfa_locked_until = CASE
        WHEN mfa_locked_until IS NOT NULL AND mfa_locked_until <= now() THEN NULL
        WHEN mfa_locked_until IS NOT NULL THEN mfa_locked_until
        WHEN mfa_failed_attempts + 1 >= $2::int
            THEN now() + make_interval(secs => $3::int)
        ELSE mfa_locked_until
    END,
    updated_at = now()
WHERE id = $1
RETURNING mfa_failed_attempts, mfa_locked_until
`

type ClaimMFAAttemptParams struct {
	ID          uuid.UUID `json:"id"`
	MaxAttempts int32     `json:"max_attempts"`
	LockSeconds int32     `json:"lock_seconds"`
}

type ClaimMFAAttemptRow struct {
	MfaFailedAttempts int32        `json:"mfa_failed_attempts"`
	MfaLockedUntil    sql.NullTime `json:"mfa_locked_until"`
}

// Takes one attempt off the account's TOTP budget, and reports what is left.
//
// Called BEFORE the code is checked, which is the whole point. The previous
// order was read the lock, check the code, then count a failure -- three
// statements, and every request that started before the first UPDATE landed
// read "not locked" and went on to verify. Measured against the real server:
// forty parallel wrong codes, thirty-six of them verified, limit five. An
// attacker holding the password -- the exact case MFA exists for -- got a few
// hundred guesses per window instead of five.
//
// One UPDATE has no such window. Concurrent updates of one row serialise in
// Postgres and each re-reads the row it is updating, so forty requests take
// the numbers one to forty and the caller refuses everything past the budget.
//
// Three cases, in the order the CASE tests them:
//
//	locked and still locked   the count keeps rising and the deadline does
//	                          NOT move, so an attacker hammering a locked
//	                          account cannot hold the owner out forever by
//	                          pushing the lock further away.
//	locked and expired        the window is over: back to one, lock cleared.
//	                          Without this the count stays at the maximum and
//	                          the next single attempt re-locks immediately.
//	not locked                count it, and lock once the budget is spent.
func (q *Queries) ClaimMFAAttempt(ctx context.Context, arg ClaimMFAAttemptParams) (ClaimMFAAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, claimMFAAttempt, arg.ID, arg.MaxAttempts, arg.LockSeconds)
	var i ClaimMFAAttemptRow
	err := row.Scan(&i.MfaFailedAttempts, &i.MfaLockedUntil)
	return i, err
}

const clearMFA = `-- name: ClearMFA :exec
UPDATE users SET mfa_secret = '', mfa_enabled = false, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearMFA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearMFA, id)
	return err
}

const clearMFAFailures = `-- name: ClearMFAFailures :exec
UPDATE users
SET mfa_failed_attempts = 0, mfa_locked_until = NULL, updated_at = now()
WHERE id = $1
`

// Called after a correct code. NIST SP 800-63B has the verifier disregard
// prior failed attempts once the user authenticates successfully.
func (q *Queries) ClearMFAFailures(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearMFAFailures, id)
	return err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
`

// Every row, including disabled and soft-deleted accounts.
//
// This is what gates /setup, and the filtered count above is why it had to
// exist. Soft-delete or disable every account -- which an administrator can do
// to their own, sole, admin account, since nothing stops them -- and the
// filtered count returns zero, /setup/status answers {"needed": true}, and
// anyone on the internet can POST /setup and be handed an administrator over
// the existing data: every ticket, every customer, every attachment.
//
// "Setup is permanently blocked once complete" is what the design says. A
// count of live accounts cannot express "permanently"; a count of rows can,
// because nothing in this system hard-deletes a user.
func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOtherActiveAdmins = `-- name: CountOtherActiveAdmins :one
SELECT COUNT(*) FROM users
WHERE role = 'admin'
  AND deleted_at IS NULL
  AND disabled = FALSE
  AND id <> $1
`

// How many administrators this instance would still have if $1 stopped being
// one.
//
// Nothing stopped an administrator disabling, demoting or deleting their own
// sole admin account: all three answered 200 or 204, the next request was 401,
// and setup does not reopen (HasUsers counts every row, deliberately). The
// instance was then left with no way in at all short of editing the database.
func (q *Queries) CountOtherActiveAdmins(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOtherActiveAdmins, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND disabled = FALSE
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    email,
    display_name,
    role,
    password_hash,
    mfa_secret,
    mfa_enabled,
    saml_subject,
    oidc_subject,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	PasswordHash string    `json:"password_hash"`
	MfaSecret    string    `json:"mfa_secret"`
	MfaEnabled   bool      `json:"mfa_enabled"`
	SamlSubject  string    `json:"saml_subject"`
	OidcSubject  string    `json:"oidc_subject"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.PasswordHash,
		arg.MfaSecret,
		arg.MfaEnabled,
		arg.SamlSubject,
		arg.OidcSubject,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET disabled = TRUE, updated_at = now() WHERE id = $1
`

func (q *Queries) DisableUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, disableUser, id)
	return err
}

const enableUser = `-- name: EnableUser :exec
UPDATE users SET disabled = FALSE, updated_at = now() WHERE id = $1
`

func (q *Queries) EnableUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, enableUser, id)
	return err
}

const getMFALock = `-- name: GetMFALock :one
SELECT mfa_failed_attempts, mfa_locked_until FROM users WHERE id = $1
`

type GetMFALockRow struct {
	MfaFailedAttempts int32        `json:"mfa_failed_attempts"`
	MfaLockedUntil    sql.NullTime `json:"mfa_locked_until"`
}

func (q *Queries) GetMFALock(ctx context.Context, id uuid.UUID) (GetMFALockRow, error) {
	row := q.db.QueryRowContext(ctx, getMFALock, id)
	var i GetMFALockRow
	err := row.Scan(&i.MfaFailedAttempts, &i.MfaLockedUntil)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.SamlSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.OidcSubject,
		&i.MfaFailedAttempts,
		&i.MfaLockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.SamlSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.OidcSubject,
		&i.MfaFailedAttempts,
		&i.MfaLockedUntil,
	)
	return i, err
}

const getUserByIDAdmin = `-- name: GetUserByIDAdmin :one
SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE id = $1
`

func (q *Queries) GetUserByIDAdmin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.SamlSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.OidcSubject,
		&i.MfaFailedAttempts,
		&i.MfaLockedUntil,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one

SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE oidc_subject = $1 AND oidc_subject != '' AND deleted_at IS NULL
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.SamlSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.OidcSubject,
		&i.MfaFailedAttempts,
		&i.MfaLockedUntil,
	)
	return i, err
}

const getUserBySAMLSubject = `-- name: GetUserBySAMLSubject :one
SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE saml_subject = $1 AND saml_subject != '' AND deleted_at IS NULL
`

func (q *Queries) GetUserBySAMLSubject(ctx context.Context, samlSubject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySAMLSubject, samlSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.SamlSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Disabled,
		&i.OidcSubject,
		&i.MfaFailedAttempts,
		&i.MfaLockedUntil,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE deleted_at IS NULL AND disabled = FALSE ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.MfaEnabled,
			&i.SamlSubject,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Disabled,
			&i.OidcSubject,
			&i.MfaFailedAttempts,
			&i.MfaLockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, email, display_name, role, password_hash, mfa_secret, mfa_enabled, saml_subject, created_at, updated_at, deleted_at, disabled, oidc_subject, mfa_failed_attempts, mfa_locked_until FROM users WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.MfaEnabled,
			&i.SamlSubject,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Disabled,
			&i.OidcSubject,
			&i.MfaFailedAttempts,
			&i.MfaLockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMFAFailure = `-- name: RecordMFAFailure :one
UPDATE users
SET mfa_failed_attempts = mfa_failed_attempts + 1,
    mfa_locked_until = CASE
        WHEN mfa_failed_attempts + 1 >= $2::int
        THEN now() + make_interval(secs => $3::int)
        ELSE mfa_locked_until
    END,
    updated_at = now()
WHERE id = $1
RETURNING mfa_failed_attempts, mfa_locked_until
`

type RecordMFAFailureParams struct {
	ID          uuid.UUID `json:"id"`
	MaxAttempts int32     `json:"max_attempts"`
	LockSeconds int32     `json:"lock_seconds"`
}

type RecordMFAFailureRow struct {
	MfaFailedAttempts int32        `json:"mfa_failed_attempts"`
	MfaLockedUntil    sql.NullTime `json:"mfa_locked_until"`
}

// Counts a failed TOTP attempt and locks the account once the threshold is
// reached. Returns the resulting lock time so the caller can refuse
// immediately without a second round trip.
//
// The count and the lock are set in one statement so concurrent attempts
// cannot both read "4 failures" and both decide they are allowed.
func (q *Queries) RecordMFAFailure(ctx context.Context, arg RecordMFAFailureParams) (RecordMFAFailureRow, error) {
	row := q.db.QueryRowContext(ctx, recordMFAFailure, arg.ID, arg.MaxAttempts, arg.LockSeconds)
	var i RecordMFAFailureRow
	err := row.Scan(&i.MfaFailedAttempts, &i.MfaLockedUntil)
	return i, err
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users SET deleted_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreUser, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $2, display_name = $3, role = $4, password_hash = $5,
    mfa_secret = $6,
    mfa_enabled = $7,
    saml_subject = $8,
    oidc_subject = $9,
    updated_at = $10
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	PasswordHash string    `json:"password_hash"`
	MfaSecret    string    `json:"mfa_secret"`
	MfaEnabled   bool      `json:"mfa_enabled"`
	SamlSubject  string    `json:"saml_subject"`
	OidcSubject  string    `json:"oidc_subject"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.PasswordHash,
		arg.MfaSecret,
		arg.MfaEnabled,
		arg.SamlSubject,
		arg.OidcSubject,
		arg.UpdatedAt,
	)
	return err
}
