// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package dbgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/lib/pq"
)

const countWebAuthnCredentialsForUser = `-- name: CountWebAuthnCredentialsForUser :one
SELECT count(*) FROM webauthn_credentials WHERE user_id = $1
`

// Whether this account has a passkey at all.
//
// This is what makes MFARequiredFor satisfiable by a passkey rather than only
// by TOTP, and it is a count rather than an EXISTS because the same question
// is asked when deciding whether removing one leaves the account with none.
func (q *Queries) CountWebAuthnCredentialsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebAuthnCredentialsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec
INSERT INTO webauthn_credentials (
    user_id, credential_id, public_key, sign_count, transports,
    aaguid, backup_eligible, backup_state, name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWebAuthnCredentialParams struct {
	UserID         uuid.UUID `json:"user_id"`
	CredentialID   []byte    `json:"credential_id"`
	PublicKey      []byte    `json:"public_key"`
	SignCount      int64     `json:"sign_count"`
	Transports     []string  `json:"transports"`
	Aaguid         []byte    `json:"aaguid"`
	BackupEligible bool      `json:"backup_eligible"`
	BackupState    bool      `json:"backup_state"`
	Name           string    `json:"name"`
}

// Records a credential after its registration ceremony has been verified.
//
// Nothing calls this until the attestation has been checked: the design's rule
// is that a staged challenge never reaches the account until the person has
// proved they hold the key, which is why TOTP grew GenerateMFASecret and
// ConfirmMFAEnrollmentWith in place of the older EnrollMFA.
func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		pq.Array(arg.Transports),
		arg.Aaguid,
		arg.BackupEligible,
		arg.BackupState,
		arg.Name,
	)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :one
DELETE FROM webauthn_credentials
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteWebAuthnCredentialParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Removes one credential, and reports whether it was this user's to remove.
//
// Scoped by user_id as well as id, in the statement rather than by a check in
// Go: an id is not an authorisation, and the caller having read the row a
// moment ago is the read-then-write shape the rest of this codebase has spent
// several rounds removing.
func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id, user_id, credential_id, public_key, sign_count, transports, aaguid, backup_eligible, backup_state, name, created_at, last_used_at FROM webauthn_credentials WHERE credential_id = $1
`

// The assertion arrives carrying a credential id and nothing else, so this is
// the lookup sign-in depends on. The unique index on credential_id serves it.
func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		pq.Array(&i.Transports),
		&i.Aaguid,
		&i.BackupEligible,
		&i.BackupState,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listWebAuthnCredentialsByUser = `-- name: ListWebAuthnCredentialsByUser :many
SELECT id, user_id, credential_id, public_key, sign_count, transports, aaguid, backup_eligible, backup_state, name, created_at, last_used_at FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at
`

// Everything this person has registered, newest last so the list reads in the
// order they added them.
func (q *Queries) ListWebAuthnCredentialsByUser(ctx context.Context, userID uuid.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			pq.Array(&i.Transports),
			&i.Aaguid,
			&i.BackupEligible,
			&i.BackupState,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWebAuthnCredential = `-- name: TouchWebAuthnCredential :exec
UPDATE webauthn_credentials
SET sign_count = $2, last_used_at = now()
WHERE id = $1
`

type TouchWebAuthnCredentialParams struct {
	ID        uuid.UUID `json:"id"`
	SignCount int64     `json:"sign_count"`
}

// Records a successful assertion: the counter the authenticator reported, and
// when it was last used.
//
// Written off the authentication path, so a sign-in never waits on it and
// never fails because of it. The counter is stored and NOT enforced — see the
// column comment in 000029 for why a "must increase" rule locks people out
// for nothing, and why a previously-non-zero counter going backwards is worth
// logging and worth refusing nothing over.
func (q *Queries) TouchWebAuthnCredential(ctx context.Context, arg TouchWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, touchWebAuthnCredential, arg.ID, arg.SignCount)
	return err
}
